# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MakananIndonesia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MakananIndonesia
pod ‘Alamofire’
pod ‘SwiftyJSON’

  target 'MakananIndonesiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MakananIndonesiaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
